trigger:
- main

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: 'formulamonkswebdev'
  imageRepository: 'formulamonkswebdev'
  containerRegistry: 'formularegistrydev.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: 'Build an image'
      inputs:
        command: build
        dockerfile: $(dockerfilePath)
        repository: $(containerRegistry)/$(imageRepository)
        tags: |
          $(tag)
          latest

    - task: Docker@2
      displayName: 'Push image'
      inputs:
        command: push
        repository: $(containerRegistry)/$(imageRepository)
        tags: |
          $(tag)
          latest
        dockerRegistryServiceConnection: $(dockerRegistryServiceConnection)