trigger:
  branches:
    include:
    - main
  paths:
    include:
    - terraform/*
    - infra-pipeline.yml

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: infra-dev-vg

stages:
- stage: Terraform
  jobs:
  - job: TerraformDeployment
    displayName: 'Terraform Deployment'
    steps:
    - checkout: self
    - script: |
        curl -sL https://releases.hashicorp.com/terraform/$(terraformVersion)/terraform_$(terraformVersion)_linux_amd64.zip -o terraform.zip
        unzip terraform.zip
        sudo mv terraform /usr/local/bin/
        terraform version
      displayName: 'Install Terraform'
      workingDirectory: $(workingDirectory)

    - script: |
        terraform init
      displayName: 'Terraform Init'
      workingDirectory: $(workingDirectory)
      env:
        env:
          ARM_CLIENT_ID: $(ARM_CLIENT_ID)
          ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
          ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
          ARM_TENANT_ID: $(ARM_TENANT_ID)

    - script: |
        terraform workspace list  || terraform workspace select $(environment)
      displayName: 'Select Terraform Workspace'
      workingDirectory: $(workingDirectory)


    - script: |
        terraform plan -out=tfplan
      displayName: 'Terraform Plan'
      workingDirectory: $(workingDirectory)

    - script: |
        terraform apply -auto-approve tfplan
      displayName: 'Terraform Apply'
      workingDirectory: $(workingDirectory)

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(workingDirectory)/tfplan'
        ArtifactName: 'tfplan'
        publishLocation: 'container'
